# SPDX-FileCopyrightText: 2026 Forkbomb BV
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "github.com/forkbombeu/credimi"
    labels:
      - "dependencies"
      - "go"
