services:
  runner_emulator:
    image: ghcr.io/forkbombeu/credimi-runner-emulator:latest
    pull_policy: always
    restart: unless-stopped
    privileged: true
    init: true
    stop_grace_period: 2m
    cpuset: "${CPUSET:-5}"
    cpus: "${CPUS:-4.0}"
    mem_reservation: "${MEM_RESERVATION:-2g}"
    shm_size: "${SHM_SIZE:-1g}"

    pids_limit: 4096
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

    devices:
      - /dev/kvm:/dev/kvm

    volumes:
      - type: bind
        source: "${HOST_AVD_HOME_PATH:-/srv/credimi/avd-home}"
        target: /avd-home
      - type: bind
        source: "${HOST_AVD_GOLDEN_PATH:-/srv/credimi/avd-golden}"
        target: /avd-golden

    environment:
      QEMU_AUDIO_DRV: none
      CREDIMI_URL: ${CREDIMI_URL:?https://credimi.io}
      CREDIMI_INTERNAL_ADMIN_KEY: ${CREDIMI_INTERNAL_ADMIN_KEY:?}
      TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS:?temporal.credimi.io:7233}
      BASE_NAME: ${BASE_NAME:?credimi}
      GOLDEN_PATH: ${GOLDEN_PATH:-/avd-golden/credimi-golden}
      CREDIMI_PB_ADMIN: ${CREDIMI_PB_ADMIN:?}
      CREDIMI_PB_PASS: ${CREDIMI_PB_PASS:?}
      CREDIMI_RUNNER_ID: ${CREDIMI_RUNNER_ID:?}
      ADB_PRIVATE_KEY: ${ADB_PRIVATE_KEY:?}
      ADB_PUBLIC_KEY: ${ADB_PUBLIC_KEY:?}
      PORT: ${PORT:-8060}
